kiran-Lenovo-Z50-70
*** Reading local file: /home/kiran/airflow/logs/dag_id=medicare_pipeline/run_id=manual__2022-09-25T07:02:51.840622+00:00/task_id=Fraud_display/attempt=1.log
[2022-09-25T12:41:38.329+0530] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: medicare_pipeline.Fraud_display manual__2022-09-25T07:02:51.840622+00:00 [queued]>
[2022-09-25T12:41:38.372+0530] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: medicare_pipeline.Fraud_display manual__2022-09-25T07:02:51.840622+00:00 [queued]>
[2022-09-25T12:41:38.372+0530] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:41:38.372+0530] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-25T12:41:38.372+0530] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-25T12:41:38.427+0530] {taskinstance.py:1389} INFO - Executing <Task(BashOperator): Fraud_display> on 2022-09-25 07:02:51.840622+00:00
[2022-09-25T12:41:38.436+0530] {standard_task_runner.py:52} INFO - Started process 73914 to run task
[2022-09-25T12:41:38.439+0530] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'medicare_pipeline', 'Fraud_display', 'manual__2022-09-25T07:02:51.840622+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/medicare_pipeline.py', '--cfg-path', '/tmp/tmpoiyap593', '--error-file', '/tmp/tmp3lu3eyc5']
[2022-09-25T12:41:38.441+0530] {standard_task_runner.py:80} INFO - Job 192: Subtask Fraud_display
[2022-09-25T12:41:38.588+0530] {task_command.py:371} INFO - Running <TaskInstance: medicare_pipeline.Fraud_display manual__2022-09-25T07:02:51.840622+00:00 [running]> on host kiran-Lenovo-Z50-70
[2022-09-25T12:41:38.744+0530] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=medicare_pipeline
AIRFLOW_CTX_TASK_ID=Fraud_display
AIRFLOW_CTX_EXECUTION_DATE=2022-09-25T07:02:51.840622+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-25T07:02:51.840622+00:00
[2022-09-25T12:41:38.747+0530] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-09-25T12:41:38.748+0530] {subprocess.py:74} INFO - Running command: ['/usr/bin/bash', '-c', '\n    source /home/kiran/project/venv/bin/activate;\n    cd //home/kiran/medicare/src_deploy/fraud_display\n    python3 manage.py runserver localhost:8004;\n    ']
[2022-09-25T12:41:38.762+0530] {subprocess.py:85} INFO - Output:
[2022-09-25T12:41:45.137+0530] {subprocess.py:92} INFO - Watching for file changes with StatReloader
[2022-09-25T12:41:45.139+0530] {subprocess.py:92} INFO - Performing system checks...
[2022-09-25T12:41:45.139+0530] {subprocess.py:92} INFO - 
[2022-09-25T12:41:46.418+0530] {subprocess.py:92} INFO - System check identified no issues (0 silenced).
[2022-09-25T12:41:47.175+0530] {subprocess.py:92} INFO - 
[2022-09-25T12:41:47.176+0530] {subprocess.py:92} INFO - You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
[2022-09-25T12:41:47.176+0530] {subprocess.py:92} INFO - Run 'python manage.py migrate' to apply them.
[2022-09-25T12:41:47.177+0530] {subprocess.py:92} INFO - September 25, 2022 - 07:11:47
[2022-09-25T12:41:47.177+0530] {subprocess.py:92} INFO - Django version 4.1.1, using settings 'fraud_display.settings'
[2022-09-25T12:41:47.178+0530] {subprocess.py:92} INFO - Starting development server at http://localhost:8004/
[2022-09-25T12:41:47.178+0530] {subprocess.py:92} INFO - Quit the server with CONTROL-C.
[2022-09-25T12:42:03.773+0530] {subprocess.py:92} INFO - Not Found: /
[2022-09-25T12:42:03.775+0530] {subprocess.py:92} INFO - [25/Sep/2022 07:12:03] "GET / HTTP/1.1" 404 2179
[2022-09-25T12:42:05.443+0530] {subprocess.py:92} INFO - Not Found: /favicon.ico
[2022-09-25T12:42:05.444+0530] {subprocess.py:92} INFO - [25/Sep/2022 07:12:05] "GET /favicon.ico HTTP/1.1" 404 2230
[2022-09-25T12:42:13.347+0530] {subprocess.py:92} INFO - [25/Sep/2022 07:12:13] "GET /np HTTP/1.1" 200 2552
[2022-09-25T12:42:30.050+0530] {local_task_job.py:226} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-09-25T12:42:30.066+0530] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 73914. PIDs of all processes in the group: [73922, 73923, 73933, 73914]
[2022-09-25T12:42:30.067+0530] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 73914
[2022-09-25T12:42:30.067+0530] {taskinstance.py:1553} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-09-25T12:42:30.067+0530] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-09-25T12:42:30.160+0530] {process_utils.py:75} INFO - Process psutil.Process(pid=73922, status='terminated', started='12:41:38') (73922) terminated with exit code None
[2022-09-25T12:42:30.161+0530] {process_utils.py:75} INFO - Process psutil.Process(pid=73914, status='terminated', exitcode=0, started='12:41:38') (73914) terminated with exit code 0
[2022-09-25T12:42:30.163+0530] {process_utils.py:75} INFO - Process psutil.Process(pid=73933, status='terminated', started='12:41:44') (73933) terminated with exit code None
[2022-09-25T12:42:30.297+0530] {process_utils.py:75} INFO - Process psutil.Process(pid=73923, status='terminated', started='12:41:38') (73923) terminated with exit code None

